#!/usr/bin/env bash
source bashlib

basedir=${0%/*}/../../../
[[ $basedir = /* ]] || basedir=$PWD/$basedir

host=snaplog.net
jettyPath=/usr/local/jetty

emit "Deploying web application" #--
    war=("$basedir/target/"*.war)
    rsync -vP --chmod=ugo=rX "$war" "$host:$jettyPath/webapps/" && \
    ssh "$host" "$(printf 'touch "$(grep -lF %q %q/contexts/*.xml 2>/dev/null)"' "${war##*/}" "$jettyPath")"
#emit -$?
